language: rust
rust:
  - stable
  - nightly
script:
  - RUST_CHAIN=$TRAVIS_RUST_VERSION ./scripts/ci-build.sh
# do not use deploy here as deploy scripts are not executed for failed builds
after_script:
  - >
    test "$TRAVIS_PULL_REQUEST" = false &&
    test "$TRAVIS_BRANCH" = master &&
    GITHUB_REPO_SLUG="$TRAVIS_REPO_SLUG" ./scripts/deploy-badges.sh
