[package]
name = "cursive-async-view"
version = "0.1.0"
authors = ["Fin Christensen <christensen.fin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cursive = "0.12.0"
log = "0.4.6"
interpolation = "0.2.0"
crossbeam = "0.7.2"
num = "0.2.0"
